#!/bin/sh

#
# Skeleton: https://gist.github.com/mrowe/8b617a8b12a6248d48b8
#

NAME=webcam
DIR=/usr/$NAME
PIDFILE=/var/run/$NAME.pid
DAEMON=${DIR}/run.py
DAEMON_ARGS="-p 8888 -a 192.168.145.24 --mode push"
STOP_SIGNAL=INT
LOG=${DIR}/$NAME.log

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

common_opts="--quiet --pidfile $PIDFILE"

do_start(){
     start-stop-daemon -S -b ${common_opts} -d ${DIR} -m -x ${DAEMON} -- ${DAEMON_ARGS} > ${LOG} 2>&1
}

do_stop(){
    start-stop-daemon --stop ${common_opts} --signal $STOP_SIGNAL --remove-pidfile
}

do_status(){
    start-stop-daemon --status $common_opts && exit_status=$? || exit_status=$?
    echo asdf $exit_status
    case "$exit_status" in
        0)
            echo "Program '$NAME' is running."
            ;;
        1)
            echo "Program '$NAME' is not running and the pid file exists."
            ;;
        3)
            echo "Program '$NAME' is not running."
            ;;
        4)
            echo "Unable to determine program '$NAME' status."
            ;;
    esac
}

case "$1" in
  status)
        do_status
        ;;
  start)
        echo -n "Starting daemon: "$NAME
        do_start
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        do_stop
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        do_stop --retry 30
        do_start
        echo "."
        ;;
  *)
        echo "Usage: "$1" {status|start|stop|restart}"
        exit 1
esac

exit 0